onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - sharp
ignoredBuiltDependencies:
  - unrs-resolver
allowBuilds:
  '@prisma/engines': true
  esbuild: false
  prisma: true
  sharp: true
  unrs-resolver: true
