onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - sharp
ignoredBuiltDependencies:
  - unrs-resolver
allowBuilds:
  '@prisma/engines': false
  prisma: false
  sharp: false
  unrs-resolver: false
